name = "website"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[pages_build_config]
build_command = "npm run pages:build"
destination_dir = ".vercel/output/static"